# Generated by Django 4.0.1 on 2022-06-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginmodule', '0011_alter_patient_health_detail_patient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_detail',
            name='gender',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
