# Generated by Django 4.0.1 on 2022-06-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginmodule', '0013_patient_health_detail_refdoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_health_detail',
            name='diagnostic',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='patient_health_detail',
            name='symptoms',
            field=models.TextField(max_length=30),
        ),
    ]
