# Generated by Django 4.0.1 on 2022-06-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginmodule', '0014_alter_patient_health_detail_diagnostic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_health_detail',
            name='schd_time',
            field=models.TextField(default=0, max_length=30),
        ),
    ]
