# Generated by Django 4.0.1 on 2022-06-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginmodule', '0015_patient_health_detail_schd_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_health_detail',
            name='print_prescription',
            field=models.TextField(default=0, max_length=30),
        ),
    ]
