# Generated by Django 4.0.1 on 2022-06-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginmodule', '0016_patient_health_detail_print_prescription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient_health_detail',
            old_name='print_prescription',
            new_name='medicine_outside',
        ),
        migrations.AddField(
            model_name='patient_health_detail',
            name='count_outside',
            field=models.TextField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='patient_health_detail',
            name='note_outside',
            field=models.TextField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='patient_health_detail',
            name='schd_outside',
            field=models.TextField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='patient_health_detail',
            name='time_outside',
            field=models.TextField(default=0, max_length=30),
        ),
    ]
