# Generated by Django 4.0.1 on 2022-07-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginmodule', '0018_alter_patient_health_detail_count_outside_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_health_detail',
            name='count_outside',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patient_health_detail',
            name='countt',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patient_health_detail',
            name='m_time',
            field=models.TextField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patient_health_detail',
            name='note',
            field=models.TextField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patient_health_detail',
            name='note_outside',
            field=models.TextField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patient_health_detail',
            name='schd_outside',
            field=models.TextField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patient_health_detail',
            name='schd_time',
            field=models.TextField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patient_health_detail',
            name='time_outside',
            field=models.TextField(max_length=30, null=True),
        ),
    ]
